import type {Metadata} from "next";
import "./globals.css";
import {Roboto} from "next/font/google";
import {Rock_Salt} from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

const rockSalt = Rock_Salt({
  subsets: ["latin"],
  weight: ["400"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <meta charSet='UTF-8' />
        <meta name='viewport' content='width=device-width, initial-scale=1.0' />

        <title>Wiktor Dawid Portfolio</title>

        <link href='https://fonts.googleapis.com/css2?family=Rock+Salt&display=swap' rel='stylesheet' />
      </head>
      <body className={`${roboto.className}`}>{children}</body>
    </html>
  );
}
