/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";
import React, {useRef, useEffect} from "react";
import {useGLTF} from "@react-three/drei";
import {useFrame, useThree} from "@react-three/fiber";
import Room from "@/public/Room.glb";

export function Room(props) {
  const {nodes, materials} = useGLTF("/Room.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Boolean.geometry}
          material={materials.drewno}
          position={[60.178, -39.143, 363.411]}
          scale={[1.559, 0.939, 0.789]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Boolean_2.geometry}
          material={materials.ściana}
          position={[39.383, -55.37, 364.503]}
        />
        <group position={[-122.125, -70.449, 257.673]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.doniczka.geometry}
            material={materials.doniczka}
            position={[0, -5.827, 0]}
            rotation={[0, 1.571, 0]}
            scale={[1, 0.817, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.kaktus.geometry}
            material={materials.krzak}
            position={[0.387, 3.83, -0.013]}
            rotation={[0, 1.571, 0]}
            scale={[1, 1.213, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.ziemia.geometry}
            material={nodes.ziemia.material}
            position={[-0.122, -0.557, -0.003]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          />
        </group>
        <group position={[-107.25, -103.566, 2.635]} rotation={[Math.PI, -1.286, Math.PI]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_2.geometry}
            material={materials.krzak}
            position={[-5.388, 2.634, 6.719]}
            rotation={[-Math.PI / 2, 0, 2.456]}
            scale={[1, 1, 3.356]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_3.geometry}
            material={materials.krzak}
            position={[-6.771, -4.061, -3.124]}
            rotation={[-Math.PI / 2, 0, 1.782]}
            scale={[1, 1, 6.061]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_4001.geometry}
            material={materials.krzak}
            position={[-1.931, 1.953, -8.731]}
            rotation={[-Math.PI / 2, 0, -0.355]}
            scale={[1, 1, 2.321]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_5001.geometry}
            material={materials.krzak}
            position={[7.653, 2.634, 2.014]}
            rotation={[-Math.PI / 2, 0, -1.942]}
            scale={[1, 1, 3.356]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_6.geometry}
            material={materials.krzak}
            position={[0.775, 2.634, -1.231]}
            rotation={[-Math.PI / 2, 0, -0.715]}
            scale={[1, 1, 3.356]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube002.geometry}
            material={materials.krzak}
            position={[2.472, 18.052, 7.087]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={[1, 1, 3.356]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_4001.geometry}
            material={materials.doniczka}
            position={[0, -34.897, 0]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Ellipse_2.geometry}
            material={materials.ziema}
            position={[-0.026, -15.243, -0.845]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dywan.geometry}
          material={materials.czarny}
          position={[88.804, -168, 171.496]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Ellipse_2001.geometry}
          material={nodes.Ellipse_2001.material}
          position={[72.133, -167.155, 181.373]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
        />
        <group position={[-113.96, -66.689, 65.833]} rotation={[0.009, -0.235, 0.026]} scale={[1, 1.01, 1]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube005.geometry}
            material={materials["Material.006"]}
            position={[-0.14, -0.329, 0]}
            rotation={[-Math.PI / 2, -0.092, Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_14003.geometry}
            material={materials["Material.005"]}
            position={[-13.206, 0.261, -0.161]}
            rotation={[-Math.PI / 2, 1.478, -Math.PI]}
          />
        </group>
        <group position={[-117.913, -66.296, 288.654]} rotation={[-0.012, 0.308, 0.026]} scale={[1, 1.01, 1]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube004.geometry}
            material={materials["Material.006"]}
            position={[-0.14, -0.329, 0]}
            rotation={[-Math.PI / 2, -0.092, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_14002.geometry}
            material={materials["Material.005"]}
            position={[-13.206, 0.261, -0.161]}
            rotation={[-Math.PI / 2, 1.478, Math.PI]}
          />
        </group>
        <group position={[-113.301, -59.137, 52.127]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_2.geometry}
            material={materials.struny}
            position={[0.004, 0.432, 0]}
            rotation={[Math.PI / 2, 0.122, Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_3001.geometry}
            material={materials.struny}
            position={[0.218, -1.309, 0]}
            rotation={[Math.PI / 2, 0.122, Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001.geometry}
            material={materials.struny}
            position={[-0.219, 2.252, 0]}
            rotation={[Math.PI / 2, 0.122, Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_16.geometry}
            material={materials.czarny}
            position={[0, 0, 0.771]}
            rotation={[Math.PI, 0, 3.019]}
          />
        </group>
        <group position={[-122.855, 13.314, 256.91]}>
          <group position={[-0.694, -9.424, -5.025]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.kartki002.geometry}
              material={materials.strony}
              position={[0, -0.067, -0.14]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
              scale={[1, 1, 0.957]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.wcięcie_i_okładka002.geometry}
              material={materials["Material.007"]}
              position={[0.05, 0.247, 1.796]}
            />
          </group>
          <group position={[-0.694, -4.445, -4.255]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.kartki001.geometry}
              material={materials.strony}
              position={[0, -0.067, -0.14]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
              scale={[1, 1, 0.957]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.wcięcie_i_okładka001.geometry}
              material={materials["Material.007"]}
              position={[0.05, 0.247, 1.796]}
            />
          </group>
          <group position={[-0.694, 0.656, -5.025]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.kartki003.geometry}
              material={materials.strony}
              position={[0, -0.067, -0.14]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
              scale={[1, 1, 0.957]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.wcięcie_i_okładka003.geometry}
              material={materials["Material.007"]}
              position={[0.05, 0.247, 1.796]}
            />
          </group>
          <group position={[-0.694, 6.099, -5.025]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.kartki004.geometry}
              material={materials.strony}
              position={[0, -0.067, -0.14]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
              scale={[1, 1, 0.957]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.wcięcie_i_okładka004.geometry}
              material={materials["Material.007"]}
              position={[0.05, 0.247, 1.796]}
            />
          </group>
          <group position={[-0.007, 0.044, 15.717]} rotation={[-1.687, 1.439, -0.065]} scale={[1.057, 1, 1]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.kartki.geometry}
              material={materials["Material.007"]}
              position={[0, -0.067, -0.14]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
              scale={[1, 0.964, 0.957]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.wcięcie_i_okładka.geometry}
              material={nodes.wcięcie_i_okładka.material}
              position={[0.05, 0.247, 1.796]}
            />
          </group>
        </group>
        <group position={[-124.985, 14.779, 96.409]} scale={2.13}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder.geometry}
            material={materials.czarny}
            position={[0.056, -7.019, -0.207]}
            rotation={[0, 1.571, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere002.geometry}
            material={materials["kula ziemska"]}
            position={[0, 2.765, 0]}
            rotation={[-2.857, -1.243, -Math.PI / 2]}
          />
        </group>
        <group position={[-115.823, -62.855, 105.226]} rotation={[0, 1.4, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_2001.geometry}
            material={materials.doniczka}
            position={[0, 8.229, 0]}
            rotation={[0, 1.57, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002.geometry}
            material={materials.czarny}
            position={[0.536, -4.018, 1.267]}
            rotation={[0, 1.57, 0]}
            scale={[1, 6.175, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Ellipse001.geometry}
            material={materials.czarny}
            position={[0.97, -18.229, 1.089]}
            rotation={[-Math.PI / 2, 0, 1.57]}
          />
        </group>
        <group position={[-58.758, -79.571, 183.419]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.góra_lapka.geometry}
            material={materials.macbook}
            position={[-0.023, -0.278, -0.031]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_14.geometry}
            material={materials.macbook}
            position={[0, -0.789, 0]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
          />
        </group>
        <group position={[135.311, -70.479, 477.115]} rotation={[0, 1.334, 0]} scale={1.079}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001.geometry}
            material={materials["Material.003"]}
            position={[130.608, -71.331, -14.786]}
            rotation={[-Math.PI / 2, 0, 1.692]}
            scale={[1, 1, 0.777]}
          />
          <group position={[141.064, -59.859, -16.337]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Ellipse_10.geometry}
              material={materials.czarny}
              position={[0.908, 0, 11.501]}
              rotation={[-Math.PI, 1.449, -Math.PI]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Ellipse_3.geometry}
              material={materials.czarny}
              position={[0.504, 0, 8.209]}
              rotation={[-Math.PI, 1.449, -Math.PI]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Ellipse_4.geometry}
              material={materials.czarny}
              position={[0.071, 0, 4.679]}
              rotation={[-Math.PI, 1.449, -Math.PI]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Ellipse_5.geometry}
              material={materials.czarny}
              position={[-0.333, 0, 1.388]}
              rotation={[-Math.PI, 1.449, -Math.PI]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Ellipse_6.geometry}
              material={materials.czarny}
              position={[-0.751, 0, -2.01]}
              rotation={[-Math.PI, 1.449, -Math.PI]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Ellipse_7.geometry}
              material={materials.czarny}
              position={[-1.138, 0, -5.168]}
              rotation={[-Math.PI, 1.449, -Math.PI]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Ellipse_8.geometry}
              material={materials.czarny}
              position={[-1.526, 0, -8.327]}
              rotation={[-Math.PI, 1.449, -Math.PI]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Ellipse_9.geometry}
              material={materials.czarny}
              position={[-1.901, 0, -11.38]}
              rotation={[-Math.PI, 1.449, -Math.PI]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_20.geometry}
            material={materials.czarny}
            position={[140.612, -71.565, -15.304]}
            rotation={[-Math.PI, 1.449, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_21.geometry}
            material={materials["Material.011"]}
            position={[140.828, -59.989, -15.213]}
            rotation={[-Math.PI, 1.449, -Math.PI]}
          />
        </group>
        <group position={[-114.485, -53.313, 180.352]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Ellipse.geometry}
            material={materials.doniczka}
            position={[-10.853, -27.454, 3.552]}
            rotation={[-Math.PI / 2, 0, 3.141]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Ellipse_2002.geometry}
            material={materials.doniczka}
            position={[11.413, 5.562, 3.648]}
            rotation={[Math.PI, -1.57, Math.PI]}
          />
          <group position={[12.919, 7.954, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.ekran.geometry}
              material={materials.czarny}
              position={[-1.709, 0, -0.001]}
              rotation={[0, 1.57, 0]}
              scale={[1.127, 1, 1]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_11.geometry}
            material={nodes.Rectangle_11.material}
            position={[-10.146, -27.454, 3.54]}
            rotation={[-Math.PI / 2, 0, 3.141]}
          />
        </group>
        <group position={[211.935, -114.915, 339.846]} rotation={[-2.981, 0.033, 3.136]} scale={0.196}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.body.geometry}
            material={materials.Material}
            position={[7.651, -12.383, -5.483]}
            scale={[0.785, 0.785, 0.936]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bridge.geometry}
            material={materials.czarny}
            position={[4.546, -184.831, 17.489]}
            rotation={[0.017, 0.037, 0]}
            scale={[0.581, 0.594, 0.211]}
          />
          <group position={[16.599, 144.721, 4.459]} scale={[0.764, 0.896, 0.761]}>
            <group position={[61.333, -282.929, 0.541]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder_7.geometry}
                material={nodes.Cylinder_7.material}
                position={[-8.914, 11.46, 0]}
                rotation={[1.553, 0, -0.017]}
                scale={[0.738, 0.341, 0.738]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder_8.geometry}
                material={nodes.Cylinder_8.material}
                position={[11.198, -13.745, 0.344]}
                rotation={[1.553, 0, -0.017]}
                scale={[0.587, 0.271, 0.587]}
              />
            </group>
            <group position={[-15.366, 258.931, 26.324]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Torus.geometry}
                material={materials.struny}
                position={[-25.683, -17.51, -0.58]}
                rotation={[0, 0.035, -1.598]}
                scale={0.667}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Torus_2.geometry}
                material={materials.struny}
                position={[-17.585, 1.475, 0.619]}
                rotation={[0, 0.035, -1.598]}
                scale={0.634}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Torus_3.geometry}
                material={materials.struny}
                position={[28.976, -18.991, -1.393]}
                rotation={[Math.PI, -0.035, -1.543]}
                scale={-0.667}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Torus_4.geometry}
                material={materials.struny}
                position={[20.084, 0.446, 0.569]}
                rotation={[Math.PI, -0.035, -1.543]}
                scale={-0.634}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.headstock.geometry}
              material={nodes.headstock.material}
              position={[-13.122, 249.181, 10.045]}
              scale={[1, 1.099, 0.287]}
            />
            <group position={[-15.618, 249.206, 13.745]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Helix.geometry}
                material={materials.czarny}
                position={[-44.858, 30.118, -1.425]}
                rotation={[0.262, -0.209, -1.518]}
                scale={0.205}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Helix_2.geometry}
                material={materials.czarny}
                position={[-39.293, 1.583, 0.598]}
                rotation={[0.262, -0.209, -1.518]}
                scale={0.205}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Helix_3.geometry}
                material={materials.czarny}
                position={[-34.208, -29.234, 3.188]}
                rotation={[0.251, -0.003, -1.52]}
                scale={0.205}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Helix_4.geometry}
                material={materials.czarny}
                position={[35.57, -30.802, 3.002]}
                rotation={[0.251, -0.003, -1.52]}
                scale={0.205}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Helix_5.geometry}
                material={materials.czarny}
                position={[39.931, 0.99, 2.351]}
                rotation={[0.251, -0.003, -1.52]}
                scale={0.205}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Helix_6.geometry}
                material={materials.czarny}
                position={[45.431, 30.812, -2.344]}
                rotation={[0.251, -0.003, -1.52]}
                scale={0.205}
              />
            </group>
            <group position={[-12.939, 249.9, 26.533]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere.geometry}
                material={materials.czarny}
                position={[-17.274, -29.189, -0.536]}
                rotation={[0, -0.13, 0]}
                scale={[0.451, 0.451, 0.197]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere_2.geometry}
                material={materials.czarny}
                position={[20.726, -29.189, -0.764]}
                rotation={[0, -0.13, 0]}
                scale={[0.451, 0.451, 0.197]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere_3.geometry}
                material={materials.czarny}
                position={[20.356, 6.951, 2.086]}
                rotation={[0, -0.13, 0]}
                scale={[0.451, 0.451, 0.197]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere_4.geometry}
                material={materials.czarny}
                position={[17.869, 28.168, 1.76]}
                rotation={[0, -0.13, 0]}
                scale={[0.451, 0.451, 0.197]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere_5.geometry}
                material={materials.czarny}
                position={[-17.827, 28.168, 0.458]}
                rotation={[0, -0.13, 0]}
                scale={[0.451, 0.451, 0.197]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere_6.geometry}
                material={materials.czarny}
                position={[-20.294, 6.898, -0.41]}
                rotation={[0, -0.13, 0]}
                scale={[0.451, 0.451, 0.197]}
              />
            </group>
            <group position={[-13.819, 248.671, 11.23]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere_2001.geometry}
                material={materials.czarny}
                position={[-51.772, 0.262, 2.286]}
                scale={[1, 1.099, 1]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere_3001.geometry}
                material={materials.czarny}
                position={[-45.961, -30.672, 2.286]}
                scale={[1, 1.099, 1]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere_4001.geometry}
                material={materials.czarny}
                position={[46.5, -30.672, 2.286]}
                rotation={[-Math.PI, 0, 0]}
                scale={[-0.974, -1.099, -1]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere_4002.geometry}
                material={materials.czarny}
                position={[52.183, 0.262, 2.286]}
                rotation={[-Math.PI, 0, 0]}
                scale={[-0.974, -1.099, -1]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere_4003.geometry}
                material={materials.czarny}
                position={[57.96, 30.672, -2.287]}
                rotation={[-Math.PI, 0, 0]}
                scale={[-0.974, -1.099, -1]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere001.geometry}
                material={materials.czarny}
                position={[-57.726, 30.672, -2.286]}
                scale={[1, 1.099, 1]}
              />
            </group>
            <group position={[-13.75, 248.545, 13.032]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder_3.geometry}
                material={materials.czarny}
                position={[-42.27, 30.366, -2.774]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[0.756, 0.688, 0.688]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder_4.geometry}
                material={materials.czarny}
                position={[-42.429, 1.18, 0.709]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[0.756, 0.688, 0.688]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder_5.geometry}
                material={materials.czarny}
                position={[-42.429, -30.367, 2.774]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[0.756, 0.688, 0.688]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder_6.geometry}
                material={materials.czarny}
                position={[42.27, -30.367, 2.774]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[0.756, 0.688, 0.688]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder_6001.geometry}
                material={materials.czarny}
                position={[42.27, 1.18, 0.709]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[0.756, 0.688, 0.688]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder_6002.geometry}
                material={materials.czarny}
                position={[42.429, 30.366, -2.774]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[0.756, 0.688, 0.688]}
              />
            </group>
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.neck.geometry}
            material={materials.drewno}
            position={[7.287, 178.37, 9.808]}
            scale={[0.801, 1.154, 0.268]}
          />
          <group position={[4.353, -90.832, 13.977]} scale={[1, 1, 0.423]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_4.geometry}
              material={materials.czarny}
              position={[0, 44.83, 0.782]}
              rotation={[0.017, 0.037, 0]}
              scale={[0.687, 0.874, 0.158]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_5.geometry}
              material={materials.czarny}
              position={[0, -44.83, -0.783]}
              rotation={[0.017, 0.037, 0]}
              scale={[0.687, 0.874, 0.158]}
            />
          </group>
          <group position={[6.26, 102.637, 26.233]} scale={[1, 1.317, 1]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.struna_1.geometry}
              material={materials.struny}
              position={[-12.507, -16.355, -2.105]}
              scale={[0.263, 0.795, 0.263]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.struna_2.geometry}
              material={materials.struny}
              position={[-6.923, -10.142, -2.47]}
              scale={[0.263, 0.807, 0.263]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.struna_4.geometry}
              material={materials.struny}
              position={[4.063, -2.329, -1.33]}
              scale={[0.263, 0.795, 0.263]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.struna_5.geometry}
              material={materials.struny}
              position={[9.394, -10.142, -2.47]}
              scale={[0.263, 0.807, 0.263]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.struna_6.geometry}
              material={materials.struny}
              position={[16.023, -16.355, -2.105]}
              scale={[0.263, 0.795, 0.263]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.struna_7.geometry}
              material={materials.struny}
              position={[-1.644, -2.329, -1.33]}
              scale={[0.263, 0.795, 0.263]}
            />
          </group>
        </group>
        <group position={[-130.157, 18.103, 202.311]} rotation={[0, 0.348, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube003.geometry}
            material={materials.drewno}
            rotation={[-Math.PI / 2, 1.427, Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_14001.geometry}
            material={materials["Material.010"]}
            position={[1.202, 0.697, -0.4]}
            rotation={[-1.218, 1.45, -1.908]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.podkładka_pod_myszke.geometry}
          material={materials.czarny}
          position={[-56.164, -80.814, 185.895]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <group position={[35.649, -170.5, 165.039]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_18001.geometry}
            material={materials["Material.002"]}
            position={[178.969, -1.5, 125.036]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={[1, 1.318, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_19.geometry}
            material={materials["Material.002"]}
            position={[178.969, -1.5, -0.028]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={[1, 1.318, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_20001.geometry}
            material={materials["Material.002"]}
            position={[178.969, -1.5, -125.286]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={[1, 1.318, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_21001.geometry}
            material={materials["Material.002"]}
            position={[143.147, -1.5, 93.976]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={[1, 1.318, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_22001.geometry}
            material={materials["Material.002"]}
            position={[143.147, -1.5, -93.635]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={[1, 1.318, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_23.geometry}
            material={materials["Material.002"]}
            position={[107.123, -1.5, -0.028]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={[1, 1.318, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_23001.geometry}
            material={materials["Material.002"]}
            position={[107.123, -1.5, -125.286]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={[1, 1.318, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_23002.geometry}
            material={materials["Material.002"]}
            position={[107.123, -1.5, 125.036]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={[1, 1.318, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_24.geometry}
            material={materials["Material.002"]}
            position={[70.999, -1.5, -93.635]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={[1, 1.318, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_24001.geometry}
            material={materials["Material.002"]}
            position={[70.999, -1.5, 93.976]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={[1, 1.318, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_25.geometry}
            material={materials["Material.002"]}
            position={[35.414, -1.5, -0.028]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={[1, 1.318, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_25001.geometry}
            material={materials["Material.002"]}
            position={[35.414, -1.5, -125.286]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={[1, 1.318, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_25002.geometry}
            material={materials["Material.002"]}
            position={[35.414, -1.5, 125.036]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={[1, 1.318, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_26.geometry}
            material={materials["Material.002"]}
            position={[-0.429, -1.5, -93.635]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={[1, 1.318, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_26001.geometry}
            material={materials["Material.002"]}
            position={[-0.429, -1.5, 93.976]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={[1, 1.318, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_27.geometry}
            material={materials["Material.002"]}
            position={[-36.107, -1.5, -0.028]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={[1, 1.318, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_27001.geometry}
            material={materials["Material.002"]}
            position={[-36.107, -1.5, -125.286]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={[1, 1.318, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_27002.geometry}
            material={materials["Material.002"]}
            position={[-36.107, -1.5, 125.036]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={[1, 1.318, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_28.geometry}
            material={materials["Material.002"]}
            position={[-72.044, -1.5, -93.635]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={[1, 1.318, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_28001.geometry}
            material={materials["Material.002"]}
            position={[-72.044, -1.5, 93.976]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={[1, 1.318, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_29.geometry}
            material={materials["Material.002"]}
            position={[-108.316, -1.5, -0.028]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={[1, 1.318, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_29001.geometry}
            material={materials["Material.002"]}
            position={[-108.316, -1.5, -125.286]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={[1, 1.318, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_29002.geometry}
            material={materials["Material.002"]}
            position={[-108.316, -1.5, 125.036]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={[1, 1.318, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_30.geometry}
            material={materials["Material.002"]}
            position={[-143.628, -1.5, -93.635]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={[1, 1.318, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_30001.geometry}
            material={materials["Material.002"]}
            position={[-143.628, -1.5, 93.976]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={[1, 1.318, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_31.geometry}
            material={materials["Material.002"]}
            position={[-178.969, -1.5, -0.028]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={[1, 1.318, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_31001.geometry}
            material={materials["Material.002"]}
            position={[-178.969, -1.5, -125.286]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={[1, 1.318, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_31002.geometry}
            material={materials["Material.002"]}
            position={[-178.969, -1.5, 125.036]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={[1, 1.318, 1]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.półka.geometry}
          material={materials.drewno}
          position={[-145.034, -2.839, 176.453]}
          rotation={[0, 1.571, 0]}
          scale={[1, 1, 2.499]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle_17.geometry}
          material={materials.drewno}
          position={[84.69, -19.932, 374.711]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.822, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle_18.geometry}
          material={materials.drewno}
          position={[6.013, -19.932, 374.711]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.822, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle_2.geometry}
          material={materials.ściana}
          position={[-141.629, -55.465, 174.464]}
          rotation={[Math.PI, -1.569, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle_3.geometry}
          material={materials.ściana}
          position={[37.846, -195.239, 175.266]}
          rotation={[-1.571, 0, 3.14]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.szyba.geometry}
          material={materials["Material.009"]}
          position={[42.69, -21.432, 365.729]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <group position={[-72.551, -127.604, 176.784]} rotation={[-Math.PI, 0.002, -Math.PI]} scale={[1, 0.919, 1.014]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.blat.geometry}
            material={materials.drewno}
            position={[0, 42.967, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.lewa_noga.geometry}
            material={materials.czarny}
            position={[3.081, -50.967, -96.114]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.74, 0.82, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.lewy_dół.geometry}
            material={materials.czarny}
            position={[-0.087, -46.092, -96.145]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1, 0.82, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.prawa_noga.geometry}
            material={materials.czarny}
            position={[3.081, -50.967, 95.099]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.74, 0.82, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.prawy_dół.geometry}
            material={materials.czarny}
            position={[-0.087, -46.092, 95.068]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1, 0.82, 1]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/RoomBlender.glb");
